camera: Fix android.hardware.cts.CameraTest#testFaceDetection
junit.framework.AssertionFailedError: Should throw an exception if face detection is not supported.

Change-Id: I2cf8d26e94c0943838db7300ab05b4c0172b15c1

Conflicts:

	camera/exynos_camera.c